# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N8pkMDWGpmnXUV_cVyhDHR4I3oJ7_Eim
"""

#bus 10
import numpy as np
import matplotlib.pyplot as plt
 
  
# creating the dataset
g2v = {'1':72.85091, '2':65.94048, '3':57.11511,'4':57.69792,'5':58.28073,'6':0,'7':0,'8':0,'9':0,'10':0,'11':0,'12':0,'13':0,'14':0,'15':0,'16':0,'17':0,'18':0,'19':0,'20':0,'21':0,'22':64.1088,'23':87.93914,'24':86.54688}
courses = list(g2v.keys())
values = list(g2v.values())

v2g = {'1':0, '2':0, '3':0,'4':0,'5':0,'6':0,'7':0,'8':0,'9':0,'10':0,'11':0,'12':0,'13':0,'14':42.96122,'15':32.47069,'16':35.69695,'17':0,'18':0,'19':0,'20':0,'21':0,'22':0,'23':0,'24':0}
cs = list(v2g.keys())
vs = list(v2g.values())
  
fig = plt.figure(figsize = (10, 5))
plt.bar(cs, vs, color ='blue',
        width = 0.8,edgecolor ='grey', label ='benefit of EVs (V2G)')
 
# creating the bar plot
plt.bar(courses, values, color ='red',
        width = 0.8,edgecolor ='grey', label ='benefit of EVCs (G2V)')
 
plt.xlabel("Time of the day/hours")
plt.ylabel("Cost of EVCs and EVs(rupees/KWh)")
plt.title("Cost Benefit Analysis at Bus 10")
plt.legend()
plt.show()

#bus 14
import numpy as np
import matplotlib.pyplot as plt
 
  
# creating the dataset
g2v = {'1':0, '2':0, '3':0,'4':39.27,'5':46.2,'6':34.485,'7':0,'8':0,'9':0,'10':56.90667,'11':93.5704,'12':133.4025,'13':0,'14':0,'15':0,'16':0,'17':0,'18':0,'19':0,'20':0,'21':0,'22':0,'23':0,'24':0}
courses = list(g2v.keys())
values = list(g2v.values())

v2g = {'1':25.9875, '2':20.79, '3':27.72,'4':0,'5':0,'6':0,'7':0,'8':0,'9':0,'10':0,'11':0,'12':0,'13':0,'14':0,'15':0,'16':41.70833,'17':17.5175,'18':21.45,'19':0,'20':0,'21':0,'22':0,'23':0,'24':0}
cs = list(v2g.keys())
vs = list(v2g.values())
  
fig = plt.figure(figsize = (10, 5))
plt.bar(cs, vs, color ='blue',
        width = 0.8,edgecolor ='grey', label ='benefit of EVs (V2G)')
 
# creating the bar plot
plt.bar(courses, values, color ='red',
        width = 0.8,edgecolor ='grey', label ='benefit of EVCs (G2V)')
 
plt.xlabel("Time of the day/hours")
plt.ylabel("Cost of EVCs and EVs(rupees/KWh)")
plt.title("Cost Benefit Analysis at Bus 14")
plt.legend()
plt.show()

#bus 17
import numpy as np
import matplotlib.pyplot as plt
 
  
# creating the dataset
g2v = {'1':0, '2':0, '3':0,'4':0,'5':0,'6':38.9928,'7':55.2398,'8':48.741,'9':0,'10':0,'11':0,'12':0,'13':0,'14':0,'15':0,'16':0,'17':0,'18':0,'19':0,'20':0,'21':0,'22':16.247,'23':33.4224,'24':30.32773}
courses = list(g2v.keys())
values = list(g2v.values())

v2g = {'1':0, '2':0, '3':0,'4':0,'5':0,'6':0,'7':0,'8':0,'9':0,'10':0,'11':0,'12':0,'13':0,'14':41.9985,'15':45.41514,'16':25.41753,'17':38.92059,'18':0,'19':0,'20':0,'21':0,'22':0,'23':0,'24':0}
cs = list(v2g.keys())
vs = list(v2g.values())
  
fig = plt.figure(figsize = (10, 5))
plt.bar(cs, vs, color ='blue',
        width = 0.8,edgecolor ='grey', label ='benefit of EVs (V2G)')
 
# creating the bar plot
plt.bar(courses, values, color ='red',
        width = 0.8,edgecolor ='grey', label ='benefit of EVCs (G2V)')
 
plt.xlabel("Time of the day/hours")
plt.ylabel("Cost of EVCs and EVs(rupees/KWh)")
plt.title("Cost Benefit Analysis at Bus 17")
plt.legend()
plt.show()

#Bus 30
import numpy as np
import matplotlib.pyplot as plt
 
  
# creating the dataset
g2v = {'1':63.225, '2':48.63461, '3':66.7375,'4':42.15,'5':30.6217,'6':42.15,'7':31.7394,'8':23.1411,'9':0,'10':0,'11':0,'12':0,'13':0,'14':0,'15':0,'16':0,'17':0,'18':0,'19':0,'20':0,'21':0,'22':0,'23':0,'24':0}
courses = list(g2v.keys())
values = list(g2v.values())

v2g = {'1':0, '2':0, '3':0,'4':0,'5':0,'6':0,'7':0,'8':0,'9':0,'10':0,'11':0,'12':0,'13':0,'14':26.9563,'15':21.8188,'16':39.5685,'17':60.8540,'18':37.1702,'19':60.3965,'20':0,'21':0,'22':0,'23':0,'24':0}
cs = list(v2g.keys())
vs = list(v2g.values())
  
fig = plt.figure(figsize = (10, 5))
plt.bar(cs, vs, color ='blue',
        width = 0.8,edgecolor ='grey', label ='benefit of EVs (V2G)')
 
# creating the bar plot
plt.bar(courses, values, color ='red',
        width = 0.8,edgecolor ='grey', label ='benefit of EVCs (G2V)')
 
plt.xlabel("Time of the day/hours")
plt.ylabel("Cost of EVCs and EVs(rupees/KWh)")
plt.title("Cost Benefit Analysis at Bus 30")
plt.legend()
plt.show()

#importing libraries
import matplotlib.pyplot as plt
import pandas as pd
from pandas import *
#uploading csv
from google.colab import files
uploaded = files.upload()
#csv to list
data = read_csv("ev1.csv")

time = data['Time in hr'].tolist()
demand = data['Demand'].tolist()
soc = data['SOC'].tolist()
mode = data['C/D'].tolist()
power = data[' P'].tolist()
#graph
plt.plot(time, demand, label = "demand", color='green', linestyle='dashed', linewidth = 1,
         marker='o', markerfacecolor='blue', markersize=6)
plt.plot(time, soc, label = "SOC",color='red', linewidth = 1, marker='o', markerfacecolor='blue', markersize=6)
plt.xlabel('time')
plt.ylabel('demand and state of charge')
plt.title('cost benefit analysis')
plt.legend()
plt.show()
mode = []
#table printing
df=pd.read_csv('ev1.csv')
df.head(28)

#importing libraries
import matplotlib.pyplot as plt
import pandas as pd
from pandas import *
#uploading csv
from google.colab import files
uploaded = files.upload()
#csv to list
data = read_csv("ev2.csv")

time = data['Time in hr'].tolist()
demand = data['Demand'].tolist()
soc = data['SOC'].tolist()
mode = data['C/D'].tolist()
power = data[' P'].tolist()
#graph
plt.plot(time, demand, label = "demand", color='green', linestyle='dashed', linewidth = 1,
         marker='o', markerfacecolor='blue', markersize=6)
plt.plot(time, soc, label = "SOC",color='red', linewidth = 1, marker='o', markerfacecolor='blue', markersize=6)
plt.xlabel('time')
plt.ylabel('demand and state of charge')
plt.title('cost benefit analysis')
plt.legend()
plt.show()
mode = []
#table printing
df=pd.read_csv('ev2.csv')
df.head(28)

#importing libraries
import matplotlib.pyplot as plt
import pandas as pd
from pandas import *
#uploading csv
from google.colab import files
uploaded = files.upload()
#csv to list
data = read_csv("ev3.csv")

time = data['Time in hr'].tolist()
demand = data['Demand'].tolist()
soc = data['SOC'].tolist()
mode = data['C/D'].tolist()
power = data[' P'].tolist()
#graph
plt.plot(time, demand, label = "demand", color='green', linestyle='dashed', linewidth = 1,
         marker='o', markerfacecolor='blue', markersize=6)
plt.plot(time, soc, label = "SOC",color='red', linewidth = 1, marker='o', markerfacecolor='blue', markersize=6)
plt.xlabel('time')
plt.ylabel('demand and state of charge')
plt.title('cost benefit analysis')
plt.legend()
plt.show()
mode = []
#table printing
df=pd.read_csv('ev3.csv')
df.head(28)

#importing libraries
import matplotlib.pyplot as plt
import pandas as pd
from pandas import *
#uploading csv
from google.colab import files
uploaded = files.upload()
#csv to list
data = read_csv("ev4.csv")

time = data['Time in hr'].tolist()
demand = data['Demand'].tolist()
soc = data['SOC'].tolist()
mode = data['C/D'].tolist()
power = data[' P'].tolist()
#graph
plt.plot(time, demand, label = "demand", color='green', linestyle='dashed', linewidth = 1,
         marker='o', markerfacecolor='blue', markersize=6)
plt.plot(time, soc, label = "SOC",color='red', linewidth = 1, marker='o', markerfacecolor='blue', markersize=6)
plt.xlabel('time')
plt.ylabel('demand and state of charge')
plt.title('cost benefit analysis')
plt.legend()
plt.show()
mode = []
#table printing
df=pd.read_csv('ev4.csv')
df.head(28)